[package]
name = "rusty-rs"
version = "0.1.0"
authors = ["Mart Roosmaa <mart@roosmaa.net>"]

[profile.release]
lto = true
opt-level = "s"

[lib]
crate-type = ["staticlib"]

[dependencies]
byteorder = { version = "1", default-features = false }
