[package]
name = "ui-patterns"
version = "0.1.0"
authors = ["Mart Roosmaa <mart@roosmaa.net>"]

## Uncomment when compiling outside of the bolos-rs workspace
# [profile.release]
# lto = true
# opt-level = "s"

[dependencies]
bolos = { path = "../../sdk/" }
